### Site Settings ###
title               : Jillian Goldberg
header-logo          : ../media/jilliangoldberg-logo.png

description         : 
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : jilliangoldberg/jilliangoldberg.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/blog.html
  - pages/projects.html
  - pages/experience.md
  - pages/chinese.html
  - pages/notes/cs61c-m.md
  - pages/notes/cs70-m.md
  - pages/notes/cs70-f.md
  - pages/notes/chinese-1a.md
  - pages/notes/cs188-m.md
  - pages/notes/ml-book.md
  - pages/notes/eecs16a-m1.md
  - pages/notes/eecs16a-m2.md
  - pages/notes/eecs16a-f.md
  - pages/notes/stat20-final.md
  - pages/notes/stat20-mt.md
  - pages/notes/cs162-mt1.md
  - pages/notes/cs162-mt2.md
  - pages/projects/cs180.md
  - pages/projects/disney-datathon.md
  - pages/projects/calhacks.md

### Author Info ###
author:
  name              : Jillian Goldberg
  image             : media/jillian_fa22.jpg
  email             : jilliangoldberg@berkeley.edu
  facebook          : jillian.goldberg.71
  github            : jilliangoldberg
  linkedin          : jilliangoldberg
  youtube           : JillianGoldberg


### Posts ###
# permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "notes"
    values:
      comments: false    


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
